---
kind: pipeline
name: default

clone:
  disable: true

workspace:
  base: /workspace
  path: src/github.com/presslabs/charts

steps:
- name: git
  pull: default
  image: plugins/git
  settings:
    depth: 0
  tags: true

- name: update-chart-index
  image: presslabs/build:stable
  pull: always
  environment:
    SSH_KEY:
      from_secret: SSH_KEY
  commands:
    - /usr/local/bin/setup-credentials-helper.sh
    - git remote set-url origin git@github.com:presslabs/charts.git
    - ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts
    - make index
    - make publish
  when:
    branch: master
---
kind: signature
hmac: 700d3ce2a0c246d2a1b19415c0f1e35da0465642994719fac1d5e03fedf7c262

...
