---
kind: pipeline
name: default

clone:
  disable: true

workspace:
  base: /workspace
  path: src/github.com/presslabs/charts

steps:
- name: git
  pull: default
  image: plugins/git
  settings:
    depth: 0
  tags: true

- name: update-chart-index
  image: presslabs/build:stable
  pull: always
  environment:
    DOCKER_HOST: unix:///workspace/docker.sock
    GOOGLE_CREDENTIALS:
      from_secret: PL_INFRA_GCR_IO_PUSH
    GIT_USER: presslabs-bot
    GIT_PASSWORD:
      from_secret: GH_PASSWORD
  commands:
    - /usr/local/bin/setup-credentials-helper.sh
    - git config --global push.default current
    - git remote set-url origin git@github.com:presslabs/charts.git
    - ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts
    - make index
    - make publish
  when:
    branch: master
---
kind: signature
hmac: b118e26862889be531464feae5831a8eb3bd41630d586d5a4c487571469114e3

...
